=== DmitrySudakov/tyler_tech/docs/efm_documenation/Artifacts/Schema/admin/RegistrationRequest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="urn:tyler:efm:services:schema:RegistrationRequest" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:common="urn:tyler:efm:services:schema:Common" xmlns:request="urn:tyler:efm:services:schema:BaseRequest" targetNamespace="urn:tyler:efm:services:schema:RegistrationRequest" elementFormDefault="qualified" id="RegistrationRequest">
	<xs:import namespace="urn:tyler:efm:services:schema:Common" schemaLocation="Common.xsd"/>
	<xs:import namespace="urn:tyler:efm:services:schema:BaseRequest" schemaLocation="BaseRequest.xsd"/>
	<xs:complexType name="RegistrationRequestType">
		<xs:complexContent>
			<xs:extension base="request:BaseRequestType">
				<xs:sequence>
					<xs:element name="RegistrationType" type="common:RegistrationType"/>
					<xs:element name="Email" type="common:REQUIRED_STRING"/>
					<xs:element name="FirstName" type="common:REQUIRED_STRING"/>
					<xs:element name="MiddleName" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="LastName" type="common:REQUIRED_STRING"/>
					<xs:element name="Password" type="common:REQUIRED_STRING" nillable="true" minOccurs="0"/>
					<xs:element name="PasswordQuestion" nillable="true" minOccurs="0">
						<xs:simpleType>
							<xs:restriction base="common:REQUIRED_STRING">
								<xs:maxLength value="256"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="PasswordAnswer" type="common:REQUIRED_STRING" nillable="true" minOccurs="0"/>
					<xs:element name="StreetAddressLine1" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="StreetAddressLine2" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="City" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="StateCode" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="ZipCode" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="CountryCode" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="FirmName" type="xs:string" nillable="true" minOccurs="0"/>
					<xs:element name="PhoneNumber" type="xs:string" nillable="true" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="RegisterUserRequest" type="RegistrationRequestType"/>
</xs:schema>

=== DmitrySudakov/tyler_tech/resources/efm_documenation/Artifacts/Sample Messages/Admin - EFM Firm Service/RegisterUser/NewIndividualUserRegistrationMessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<RegisterUserRequest xmlns="urn:tyler:efm:services:schema:RegistrationRequest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:tyler:efm:services:schema:RegistrationRequest ..\..\..\Schema\Admin\RegistrationRequest.xsd">
	<RegistrationType>Individual</RegistrationType>
	<Email>john.doe@tylertech.com</Email>
	<FirstName>John</FirstName>
	<MiddleName/>
	<LastName>Doe</LastName>
	<Password>@BC123xyz</Password>
	<PasswordQuestion>What color is the sky?</PasswordQuestion>
	<PasswordAnswer>blue</PasswordAnswer>
	<StreetAddressLine1>6500 International Pkwy</StreetAddressLine1>
	<StreetAddressLine2>Suite 2000</StreetAddressLine2>
	<City>Plano</City>
	<StateCode>TX</StateCode>
	<ZipCode>75093</ZipCode>
	<CountryCode>US</CountryCode>
	<FirmName></FirmName>
	<PhoneNumber>9727133770</PhoneNumber>
</RegisterUserRequest>
